// Company pool for Rapids Run.
// Source: https://docs.google.com/spreadsheets/d/1wxFpDorQXUKdqXlMUxDKo6hr8XpT2mVvNvwjlGa3tz4
// type: "good" (clean/scandal-free) or "bad" (scandal-plagued); points applied on hit.
const COMPANIES = [
  { "name": "Anthropic", "type": "good", "points": 450, "category": "Tech / AI" },
  { "name": "Personio", "type": "good", "points": 300, "category": "HR Tech" },
  { "name": "Apple", "type": "good", "points": 300, "category": "Big Tech" },
  { "name": "Microsoft", "type": "good", "points": 400, "category": "Big Tech" },
  { "name": "Nvidia", "type": "good", "points": 500, "category": "Hardware / AI" },
  { "name": "Stripe", "type": "good", "points": 400, "category": "Fintech" },
  { "name": "Spotify", "type": "good", "points": 350, "category": "Entertainment" },
  { "name": "Costco", "type": "good", "points": 400, "category": "Retail" },
  { "name": "Patagonia", "type": "good", "points": 250, "category": "Apparel" },
  { "name": "Berkshire Hathaway", "type": "good", "points": 350, "category": "Holding" },
  { "name": "Salesforce", "type": "good", "points": 200, "category": "Enterprise Software" },
  { "name": "Google (Alphabet)", "type": "good", "points": 500, "category": "Tech" },
  { "name": "ASML", "type": "good", "points": 250, "category": "Semiconductor" },
  { "name": "Shopify", "type": "good", "points": 250, "category": "E-Commerce" },
  { "name": "Figma", "type": "good", "points": 100, "category": "Design Software" },
  { "name": "Databricks", "type": "good", "points": 400, "category": "Data / AI" },
  { "name": "Canva", "type": "good", "points": 400, "category": "Software" },
  { "name": "Duolingo", "type": "good", "points": 400, "category": "EdTech" },
  { "name": "OpenAI", "type": "good", "points": 450, "category": "Tech / AI" },
  { "name": "Visa", "type": "good", "points": 350, "category": "Financial Services" },
  { "name": "Novo Nordisk", "type": "good", "points": -100, "category": "Pharma" },
  { "name": "Siemens", "type": "good", "points": 300, "category": "Industrial" },
  { "name": "Hubspot", "type": "good", "points": 150, "category": "Software" },
  { "name": "AirBnB", "type": "good", "points": 300, "category": "Hospitality" },
  { "name": "Lego", "type": "good", "points": 350, "category": "Consumer Goods" },
  { "name": "Wirecard", "type": "bad", "points": -500, "category": "Fintech Fraud" },
  { "name": "Enron", "type": "bad", "points": -500, "category": "Energy Fraud" },
  { "name": "Lehman Brothers", "type": "bad", "points": -500, "category": "Banking Collapse" },
  { "name": "FTX", "type": "bad", "points": -450, "category": "Crypto Fraud" },
  { "name": "Theranos", "type": "bad", "points": -500, "category": "Biotech Fraud" },
  { "name": "WeWork", "type": "bad", "points": -150, "category": "Real Estate / Governance" },
  { "name": "Bernie Madoff Investment", "type": "bad", "points": -500, "category": "Ponzi Scheme" },
  { "name": "WorldCom", "type": "bad", "points": -500, "category": "Telecom Accounting" },
  { "name": "Parmalat", "type": "bad", "points": -400, "category": "Food / Fraud" },
  { "name": "Luckin Coffee", "type": "bad", "points": -50, "category": "Retail Fraud" },
  { "name": "SVB (Silicon Valley Bank)", "type": "bad", "points": -350, "category": "Banking Run" },
  { "name": "Credit Suisse", "type": "bad", "points": -350, "category": "Financial Mismanagement" },
  { "name": "Tyco", "type": "bad", "points": -350, "category": "Corporate Looting" },
  { "name": "HealthSouth", "type": "bad", "points": -350, "category": "Healthcare Fraud" },
  { "name": "Bear Stearns", "type": "bad", "points": -450, "category": "Investment Banking" },
  { "name": "Greensill Capital", "type": "bad", "points": -450, "category": "Supply Chain Finance" },
  { "name": "OneCoin", "type": "bad", "points": -500, "category": "Crypto Scam" },
  { "name": "Washington Mutual", "type": "bad", "points": -450, "category": "Subprime Mortgage" },
  { "name": "Nikola Motors", "type": "bad", "points": -400, "category": "EV Fraud" },
  { "name": "Lordstown Motors", "type": "bad", "points": -400, "category": "EV Collapse" },
  { "name": "Sears", "type": "bad", "points": -300, "category": "Retail Collapse" },
  { "name": "BlockFi", "type": "bad", "points": -350, "category": "Crypto Bankruptcy" },
  { "name": "Celsius Network", "type": "bad", "points": -350, "category": "Crypto Collapse" },
  { "name": "Carillion", "type": "bad", "points": -450, "category": "Construction Debt" },
  { "name": "Thomas Cook", "type": "bad", "points": -350, "category": "Travel Bankruptcy" }
];
